sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t iii5412/docker-react-app -f DockerFile.dev .

script:
  - docker run -e CI=true iii5412/docker-react-app npm run test -- --coverage 
  #CI=true는 travis CI에서 꼭 줘야하는 옵션이고 -- --coverage는 테스트 결과를 자세히 보기위한 옵션이다.

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Docker-react-app-env
  bucket_name: elasticbeanstalk-ap-northeast-2-492943349653
  bucket_path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY2
  secret_access_key: $AWS_SECRET_ACCESS_KEY2
